# Default values for krateo-composition-azuredevops-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Azure DevOps Configuration
azureDevOps:
  # @param {string} organization - Replace with your Azure DevOps organization name
  organization: "krateo-kog"

# Team Project Configuration
teamProject:
  # @param {boolean} teamProject.verbose - Enable verbose logging
  verbose: true # Enable verbose logging
  # @param {string} teamProject.name - Name of the Azure DevOps Team Project
  name: "krateo-project-from-composition"
  # @param {string} teamProject.description - Description for the Azure DevOps Team Project
  description: "Created by Krateo Composition"
  # @param {string} teamProject.visibility - Visibility of the Azure DevOps Team Project
  visibility: private
  # @param {object} teamProject.sourceControlType - Source control type for the Azure DevOps Team Project
  sourceControlType: "Git"
  # @param {string} teamProject.templateTypeId - Template type ID for the Azure DevOps Team Project
  templateTypeId: 6b724908-ef14-45cf-84f8-768b5384da45

# Environment Configuration
environment:
  # @param {boolean} environment.verbose - Enable verbose logging
  verbose: true # Enable verbose logging
  # @param {string} environment.name - Name of the Azure DevOps Environment
  name: "krateo-env-from-composition"
  # @param {string} environment.description - Description for the Azure DevOps Environment
  description: "Created by Krateo Composition"


