apiVersion: azuredevops.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ .Values.gitRepository.name | lower }}
spec:
  authenticationRef:
    name: {{ .Values.azureDevOps.patSecretRef.name }}
    namespace: {{ .Values.azureDevOps.patSecretRef.namespace }}
  organization: {{ .Values.azureDevOps.organization }}
  project: {{ .Values.teamProject.name }}
  name: {{ .Values.gitRepository.name }}
  templateRepo:
    url: {{ .Values.gitRepository.templateRepoUrl }}
    branch: {{ .Values.gitRepository.templateRepoBranch }}
