apiVersion: composition.krateo.io/v0-0-1
kind: AzuredevopsStarter
metadata:
  labels:
    krateo.io/composition-version: v0-0-1
  name: azuredevops-starter
  namespace: azuredevops-system
spec:
  azureDevOps:
    organization: "krateo-kog"
  
  teamProject:
    verbose: true
    name: "project-from-composition"
    #description: "Created by Krateo Composition"

  environment:
    verbose: true
    name: "environment-from-composition"
    description: "Created by Krateo Composition"
    
  gitRepository:
    verbose: true
    name: "repo-from-composition"
    apiVersion: "7.2-preview.2"
    initialize: true
    defaultBranch: "refs/heads/test-branch"

  pipeline:
    verbose: true
    apiVersion: "7.2-preview.1"
    name: "pipeline-from-composition"
    folder: "test-folder-kog"
  
  pipelinePermission:
    verbose: true
    apiVersion: "7.2-preview.1"
    name: "pipelinepermission-from-composition"
