apiVersion: composition.krateo.io/v0-0-1
kind: AzuredevopsCompositionExample
metadata:
  labels:
    krateo.io/composition-version: v0-0-1
  name: azuredevops-composition-example
  namespace: azuredevops-example
spec:
  azureDevOps:
    organization: "krateo-kog"
  
  teamProject:
    verbose: true
    name: "krateo-project-from-composition"
    description: "Created by Krateo Composition"

  environment:
    verbose: true
    name: "krateo-env-from-composition"
    description: "Created by Krateo Composition"
    
  gitRepository:
    verbose: true
    name: "krateo-repo-from-composition"
    apiVersion: "7.2-preview.2"
    initialize: true
    defaultBranch: "refs/heads/test-branch"
