{{- $teamProject := lookup "azuredevops.krateo.io/v1alpha1" "TeamProject" .Release.Namespace (.Values.teamProject.name | lower) }}
{{- if and $teamProject $teamProject.status $teamProject.status.id }}
# The above guard is needed to ensure that the Team Project is created before the GitRepository.
# Otherwise, the GitRepository creation will fail to create if it happens before the TeamProject is created on Azure DevOps.

apiVersion: azuredevops.kog.krateo.io/v1alpha1
kind: GitRepository
metadata:
  name: {{ .Values.gitRepository.name | lower }}
  annotations:
    krateo.io/connector-verbose: "{{ .Values.gitRepository.verbose }}"
spec:
  authenticationRefs:
    basicAuthRef: azure-devops-basic-auth

  api-version: {{ .Values.gitRepository.apiVersion | default "7.2-preview.2" }}
  organization: {{ .Values.azureDevOps.organization | lower }}
  projectId: {{ .Values.teamProject.name | lower }}

  name: {{ .Values.gitRepository.name | lower }}
  initialize: {{ .Values.gitRepository.initialize | default true }}
  defaultBranch: {{ .Values.gitRepository.defaultBranch | default "refs/heads/main" }}

{{- end }}
