{{- $gitRepository := lookup "azuredevops.kog.krateo.io/v1alpha1" "GitRepository" .Release.Namespace (.Values.gitRepository.name | lower) }}
{{- if and $gitRepository $gitRepository.status.id }}
apiVersion: azuredevops.kog.krateo.io/v1alpha1
kind: Pipeline
metadata:
  name: {{ .Values.pipeline.name | lower }}
  annotations:
    krateo.io/connector-verbose: "{{ .Values.pipeline.verbose }}"
spec:
  authenticationRefs:
    basicAuthRef: azure-devops-basic-auth 
  
  api-version: {{ .Values.pipeline.apiVersion }}
  organization: {{ .Values.azureDevOps.organization }} 
  project: {{ .Values.teamProject.name }}
  
  configuration:
    path: {{ .Values.pipeline.configuration.path }}
    repository: 
      id: {{ $gitRepositoryId.status.id }}
      type: {{ .Values.pipeline.configuration.repository.type }}
    type: {{ .Values.pipeline.configuration.type }}

  name: {{ .Values.pipeline.name }}
{{- end }}
