kind: Button
apiVersion: widgets.templates.krateo.io/v1beta1
metadata:
  name: azuredevops-starter-panel-button-schema-notordered
  namespace: azuredevops-system
spec:
  widgetData:
    icon: fa-trash
    type: default
    shape: circle
    clickActionId: cleanup
    actions:
      rest:
        - id: cleanup
          resourceRefId: cleanup
          type: rest
          onSuccessNavigateTo: /templates
  resourcesRefs:
    - id: cleanup
      apiVersion: templates.krateo.io/v1
      resource: restactions
      name: azuredevops-starter-restaction-cleanup-schema-notordered
      namespace: azuredevops-system
      verb: GET