apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: azuredevops-starter-compositiondefinition
  namespace: azuredevops-system
spec:
  api:
  - name: getCompositionDefinition
    path: "/apis/core.krateo.io/v1alpha1/namespaces/azuredevops-system/compositiondefinitions/azuredevops-starter"
    verb: GET
    headers:
    - 'Accept: application/json'