apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: azuredevops-starter-restaction-cleanup-schema-notordered
  namespace: azuredevops-system
spec:
  api:
  - name: deletePanel
    path: "/apis/widgets.templates.krateo.io/v1beta1/namespaces/azuredevops-system/panels/azuredevops-starter-panel-schema-notordered"
    verb: DELETE
  - name: deletePanelParagraph
    path: "/apis/widgets.templates.krateo.io/v1beta1/namespaces/azuredevops-system/paragraphs/azuredevops-starter-panel-paragraph-schema-notordered"
    verb: DELETE
  - name: deletePanelButton
    path: "/apis/widgets.templates.krateo.io/v1beta1/namespaces/azuredevops-system/buttons/azuredevops-starter-panel-button-schema-notordered"
    verb: DELETE